<?php

/**
 * @file
 * dynamic_user_profile_editor.install
 */

/**
 * Implements hook_install().
 */
function dynamic_user_profile_editor_install() {
  // Enable jsonapi_views plugin.
  $config = \Drupal::service('config.factory')->getEditable('views.settings');
  $display_extenders = $config->get('display_extenders') ?: [];
  $display_extenders[] = 'webform_popup_extender';
  $config->set('display_extenders', $display_extenders);
  $config->save();
}

/**
 * Implements hook_uninstall().
 */
function dynamic_user_profile_editor_uninstall() {
  // Disable jsonapi_views plugin.
  $config = \Drupal::service('config.factory')->getEditable('views.settings');
  $display_extenders = $config->get('display_extenders') ?: [];
  $key = array_search('webform_popup_extender', $display_extenders);
  if ($key !== FALSE) {
    unset($display_extenders[$key]);
    $config->set('display_extenders', $display_extenders);
    $config->save();
  }
}

/**
 * Enable jsonapi_views display extender.
 */
function dynamic_user_profile_editor_update_8001() {
  // Enable jsonapi_views plugin.
  $config = \Drupal::service('config.factory')->getEditable('views.settings');
  $display_extenders = $config->get('display_extenders') ?: [];
  $display_extenders[] = 'webform_popup_extender';
  $config->set('display_extenders', $display_extenders);
  $config->save();
}
